### ISSUE TITLE
float math function missed?

### ISSUE THREAD

**Issue by Roger-luo** [torch/TH#3]
Hi I was reading the source, and I'm a little bit confused about here in `generic/THTensorMath.c`

```
#define LAB_IMPLEMENT_BASIC_FUNCTION(NAME, CFUNC)             \
  void THTensor_(NAME)(THTensor *r_, THTensor *t)                \
  {                                                           \
    THTensor_(resizeAs)(r_, t);                               \
    TH_TENSOR_APPLY2(num, t, num, r_, *r__data = CFUNC(*t_data);); \
  }                                                           \
```
And for c functions like abs, it seems that only double type like `abs` is implemented by  

```
LAB_IMPLEMENT_BASIC_FUNCTION(abs, fabs)
```

But for `float` type, the function `fabsf` is not implemented. I know this is not a big problem, but just want to know if it is true? or there are some other definitions....

**Comment by PhilippPelz** [comment]
C++ has overloads, see http://www.cplusplus.com/reference/cmath/fabs/

**Comment by Roger-luo** [comment]
OK, I get it, thanks!
